// AUTO-GENERATED by rebuild_registry_from_txt.py
// DO NOT EDIT MANUALLY
import cat_as_armas_da_luz from './catecumenato/as-armas-da-luz.json';
import cat_assim_fala_o_amem from './catecumenato/assim-fala-o-amem.json';
import cat_bendito_seja_deus from './catecumenato/bendito-seja-deus.json';
import cat_como_o_impulso_que_sente_a_ira from './catecumenato/como-o-impulso-que-sente-a-ira.json';
import cat_como_ovelha_que_ve from './catecumenato/como-ovelha-que-ve.json';
import cat_consolai_o_meu_povo from './catecumenato/consolai-o-meu-povo.json';
import cat_debora from './catecumenato/debora.json';
import cat_eis_o_meu_servo from './catecumenato/eis-o-meu-servo.json';
import cat_eis_que_o_nosso_espelho_e_o_senhor from './catecumenato/eis-que-o-nosso-espelho-e-o-senhor.json';
import cat_escutai_ilhas_de_longe from './catecumenato/escutai-ilhas-de-longe.json';
import cat_hino_a_cruz_gloriosa from './catecumenato/hino-a-cruz-gloriosa.json';
import cat_jaco from './catecumenato/jaco.json';
import cat_nao_sofras_pelos_malvados from './catecumenato/nao-sofras-pelos-malvados.json';
import cat_ninguem_pode_servir_a_dois_senhores from './catecumenato/ninguem-pode-servir-a-dois-senhores.json';
import cat_o_combate_escatologico from './catecumenato/o-combate-escatologico.json';
import cat_o_lagareiro from './catecumenato/o-lagareiro.json';
import cat_o_mesmo_deus from './catecumenato/o-mesmo-deus.json';
import cat_o_semeador from './catecumenato/o-semeador.json';
import cat_o_senhor_me_deu from './catecumenato/o-senhor-me-deu.json';
import cat_o_senhor_meu_coracao_nao_e_pretensioso from './catecumenato/o-senhor-meu-coracao-nao-e-pretensioso.json';
import cat_quando_dormia from './catecumenato/quando-dormia.json';
import cat_senhor_tu_me_escrutas_e_conheces from './catecumenato/senhor-tu-me-escrutas-e-conheces.json';
import cat_senta_te_solitario_e_silencioso from './catecumenato/senta-te-solitario-e-silencioso.json';
import cat_shema_israel from './catecumenato/shema-israel.json';
import cat_tu_cobriste_de_vergonha_a_morte from './catecumenato/tu-cobriste-de-vergonha-a-morte.json';
import cat_tu_es_digno_de_receber_o_livro from './catecumenato/tu-es-digno-de-receber-o-livro.json';
import el_a_ceia_do_cordeiro from './eleicao/a-ceia-do-cordeiro.json';
import el_a_cordeira_de_deus from './eleicao/a-cordeira-de-deus.json';
import el_a_pomba_voou from './eleicao/a-pomba-voou.json';
import el_a_voz_do_meu_amado from './eleicao/a-voz-do-meu-amado.json';
import el_abba_pai from './eleicao/abba-pai.json';
import el_como_condenados_a_morte from './eleicao/como-condenados-a-morte.json';
import el_como_escorre_o_mel from './eleicao/como-escorre-o-mel.json';
import el_como_lirio_entre_espinhos from './eleicao/como-lirio-entre-espinhos.json';
import el_estendo_minhas_maos from './eleicao/estendo-minhas-maos.json';
import el_formosa_es_amiga_minha from './eleicao/formosa-es-amiga-minha.json';
import el_hino_a_caridade from './eleicao/hino-a-caridade.json';
import el_jesus_percorria_todas_as_cidades from './eleicao/jesus-percorria-todas-as-cidades.json';
import el_nao_resistais_ao_mal from './eleicao/nao-resistais-ao-mal.json';
import el_noli_me_tangere from './eleicao/noli-me-tangere.json';
import el_o_espirito_do_senhor_esta_sobre_mim from './eleicao/o-espirito-do-senhor-esta-sobre-mim.json';
import el_o_messias_leao_para_vencer from './eleicao/o-messias-leao-para-vencer.json';
import el_roubaste_o_meu_coracao from './eleicao/roubaste-meu-coracao.json';
import el_sermao_da_montanha from './eleicao/sermao-da-montanha.json';
import el_tu_es_a_minha_esperanca_senhor from './eleicao/tu-es-a-minha-esperanca-senhor.json';
import li_aleluia_interlecional from './liturgia/aleluia-interleccional.json';
import li_aleluia_pascal from './liturgia/aleluia-pascal.json';
import li_aleluia_pascal_ii from './liturgia/aleluia-pascal-ii.json';
import li_anafora_do_sal from './liturgia/anafora-do-sal.json';
import li_antifona_versiculo_antes_do_evangelho from './liturgia/antifona-versiculo-antes-do-evangelho.json';
import li_bencao_da_agua from './liturgia/bencao-da-agua.json';
import li_bencao_penitencial from './liturgia/bencao-penitencial.json';
import li_cordeiro_de_deus from './liturgia/cordeiro-de-deus.json';
import li_credo from './liturgia/credo.json';
import li_gloria_a_deus_no_alto_do_ceu from './liturgia/gloria-a-deus-no-alto-do-ceu.json';
import li_hino_das_laudes_de_pentecostes from './liturgia/hino-das-laudes-de-pentecostes.json';
import li_ladainha_de_todos_os_santos from './liturgia/ladainha-de-todos-os-santos.json';
import li_ladainha_penitencial_i from './liturgia/ladainha-penitencial-i.json';
import li_ladainha_penitencial_ii from './liturgia/ladainha-penitencial-ii.json';
import li_oracao_eucaristica_ii from './liturgia/oracao-eucaristica-ii.json';
import li_oracao_eucaristica_iv from './liturgia/oracao-eucaristica-iv.json';
import li_pai_nosso from './liturgia/pai-nosso.json';
import li_preconio_pascal from './liturgia/preconio-pascal.json';
import li_prefacio_da_pascoa_i from './liturgia/prefacio-da-pascoa-i.json';
import li_prefacio_do_advento_i from './liturgia/prefacio-do-advento-i.json';
import li_prefacio_do_advento_ii from './liturgia/prefacio-do-advento-ii.json';
import li_prefacio_do_natal_do_senhor_i from './liturgia/prefacio-do-natal-do-senhor-i.json';
import li_salmodia_para_as_oracoes_universais from './liturgia/salmodia-para-as-oracoes-universais.json';
import li_salmodia_para_o_salmo_responsorial from './liturgia/salmodia-para-o-salmo-responsorial.json';
import li_santo_1982 from './liturgia/santo-1982.json';
import li_santo_1988 from './liturgia/santo-1988.json';
import li_santo_hebraico from './liturgia/santo-hebraico.json';
import li_santo_palestina_74 from './liturgia/santo-palestina-74.json';
import li_santo_palomeras_65 from './liturgia/santo-palomeras-65.json';
import li_santo_roma_77 from './liturgia/santo-roma-77.json';
import li_te_deum from './liturgia/te-deum.json';
import pre_a_cabana_dos_pastores from './pre-catecumenato/a-cabana-dos-pastores.json';
import pre_a_ceifa_das_nacoes from './pre-catecumenato/a-ceifa-das-nacoes.json';
import pre_a_marcha_e_dura from './pre-catecumenato/a-marcha-e-dura.json';
import pre_a_espada from './pre-catecumenato/a-espada.json';
import pre_a_ninguem_demos_ocasiao_de_tropeco from './pre-catecumenato/a-ninguem-demos-ocasiao-de-tropeco.json';
import pre_a_ti_levanto_meus_olhos from './pre-catecumenato/a-ti-levanto-meus-olhos.json';
import pre_a_ti_senhor_com_minha_voz_gritando_imploro from './pre-catecumenato/a-ti-senhor-com-minha-voz-gritando-imploro.json';
import pre_a_ti_senhor_levanto_minha_alma from './pre-catecumenato/a-ti-senhor-levanto-minha-alma.json';
import pre_a_ti_senhor_se_deve_o_louvor_em_siao from './pre-catecumenato/a-ti-senhor-se-deve-o-louvor-em-siao.json';
import pre_a_vitima_pascal from './pre-catecumenato/a-vitima-pascal.json';
import pre_abraao from './pre-catecumenato/abraao.json';
import pre_aclamai_o_senhor from './pre-catecumenato/aclamai-o-senhor.json';
import pre_akeda from './pre-catecumenato/akeda.json';
import pre_alcai_o_portas from './pre-catecumenato/alcai-o-portas.json';
import pre_aleluia_bendizei_o_senhor from './pre-catecumenato/aleluia-bendizei-o-senhor.json';
import pre_aleluia_ja_chegou_o_reino from './pre-catecumenato/aleluia-ja-chegou-o-reino.json';
import pre_aleluia_louvai_o_senhor from './pre-catecumenato/aleluia-louvai-o-senhor.json';
import pre_amem_amem_amem from './pre-catecumenato/amem-amem-amem.json';
import pre_amo_o_senhor from './pre-catecumenato/amo-o-senhor.json';
import pre_ao_despertar from './pre-catecumenato/ao-despertar.json';
import pre_ate_quando from './pre-catecumenato/ate-quando.json';
import pre_ave_maria_i from './pre-catecumenato/ave-maria-i.json';
import pre_ave_maria_ii_1984 from './pre-catecumenato/ave-maria-ii-1984.json';
import pre_babilonia_criminal from './pre-catecumenato/babilonia-criminal.json';
import pre_balaao from './pre-catecumenato/balaao.json';
import pre_bendirei_o_senhor_em_todo_tempo from './pre-catecumenato/bendirei-o-senhor-em-todo-tempo.json';
import pre_bendita_es_tu_maria from './pre-catecumenato/bendita-es-tu-maria.json';
import pre_bendito_sejas_senhor from './pre-catecumenato/bendito-sejas-senhor.json';
import pre_bendize_minha_alma_a_iahweh from './pre-catecumenato/bendize-minha-alma-a-iahweh.json';
import pre_benedictus from './pre-catecumenato/benedictus.json';
import pre_canta_a_iahweh_jerusalem from './pre-catecumenato/canta-a-iahweh-jerusalem.json';
import pre_cantico_de_ana from './pre-catecumenato/cantico-de-ana.json';
import pre_cantico_dos_tres_jovens from './pre-catecumenato/cantico-dos-tres-jovens.json';
import pre_canto_de_moises from './pre-catecumenato/canto-de-moises.json';
import pre_caritas_christi_urget_nos from './pre-catecumenato/caritas-christi-urget-nos.json';
import pre_chegue_a_tua_presenca_meu_clamor from './pre-catecumenato/chegue-a-tua-presenca-o-meu-clamor.json';
import pre_como_a_corca from './pre-catecumenato/como-a-corca.json';
import pre_como_e_maravilhoso from './pre-catecumenato/como-e-maravilhoso.json';
import pre_como_sao_amaveis_tuas_moradas from './pre-catecumenato/como-sao-amaveis-tuas-moradas.json';
import pre_confessei_a_ti_o_meu_pecado from './pre-catecumenato/confessei-a-ti-o-meu-pecado.json';
import pre_dayenu from './pre-catecumenato/dayenu.json';
import pre_de_profundis from './pre-catecumenato/de-profundis.json';
import pre_dia_de_repouso from './pre-catecumenato/dia-de-repouso.json';
import pre_diante_dos_anjos from './pre-catecumenato/diante-dos-anjos.json';
import pre_diz_o_senhor_ao_meu_senhor from './pre-catecumenato/diz-o-senhor-ao-meu-senhor.json';
import pre_dizei_aos_de_coracao_cansado from './pre-catecumenato/dizei-aos-de-coracao-cansado.json';
import pre_e_paciente from './pre-catecumenato/e-paciente.json';
import pre_eis_me_aqui_que_venho_em_breve from './pre-catecumenato/eis-me-aqui-que-venho-em-breve.json';
import pre_eli_eli_lama_sabactani from './pre-catecumenato/eli-eli-lama-sabatani.json';
import pre_em_meio_a_multidao from './pre-catecumenato/em-meio-a-multidao.json';
import pre_em_tua_luz_senhor_vemos_a_luz from './pre-catecumenato/em-tua-luz-senhor-vemos-a-luz.json';
import pre_em_uma_noite_escura from './pre-catecumenato/em-uma-noite-escura.json';
import pre_encontraram_se_dois_anjos from './pre-catecumenato/encontraram-se-dois-anjos.json';
import pre_esconde_me_no_oculto_de_tua_tenda from './pre-catecumenato/esconde-me-no-oculto-de-tua-tenda.json';
import pre_esperei_esperei_no_senhor from './pre-catecumenato/esperei-esperei-no-senhor.json';
import pre_estao_rotas_minhas_ataduras from './pre-catecumenato/estao-rotas-minhas-ataduras.json';
import pre_este_e_o_dia_que_fez_o_senhor from './pre-catecumenato/este-e-o-dia-que-fez-o-senhor.json';
import pre_este_e_o_meu_mandamento from './pre-catecumenato/este-e-o-meu-mandamento.json';
import pre_estou_chamando_te from './pre-catecumenato/estou-chamando-te.json';
import pre_eu_te_amo_senhor from './pre-catecumenato/eu-te-amo-senhor.json';
import pre_eu_venho_reunir from './pre-catecumenato/eu-venho-reunir.json';
import pre_evenu_shalom_alehem from './pre-catecumenato/evenu-shalom-alehem.json';
import pre_exultai_justos_no_senhor from './pre-catecumenato/exultai-justos-no-senhor.json';
import pre_felicidade_para_o_homem from './pre-catecumenato/felicidade-para-o-homem.json';
import pre_feliz_o_homem from './pre-catecumenato/feliz-o-homem.json';
import pre_filhas_de_jerusalem from './pre-catecumenato/filhas-de-jerusalem.json';
import pre_foge_o_meu_amado from './pre-catecumenato/foge-o-meu-amado.json';
import pre_gracas_a_iahweh from './pre-catecumenato/gracas-a-iahweh.json';
import pre_gritai_jubilosos from './pre-catecumenato/gritai-jubilosos.json';
import pre_hino_a_cristo_luz from './pre-catecumenato/hino-a-cristo-luz.json';
import pre_hino_a_kenosis from './pre-catecumenato/hino-a-kenosis.json';
import pre_hino_da_ascensao from './pre-catecumenato/hino-da-ascensao.json';
import pre_hino_da_pascoa from './pre-catecumenato/hino-da-pascoa.json';
import pre_hino_do_advento from './pre-catecumenato/hino-do-advento.json';
import pre_iahweh_tu_es_meu_deus from './pre-catecumenato/iahweh-tu-es-meu-deus.json';
import pre_ide_e_anunciai_a_meus_irmaos from './pre-catecumenato/ide-e-anunciai-a-meus-irmaos.json';
import pre_improperios from './pre-catecumenato/improperios.json';
import pre_ja_vem_o_meu_deus from './pre-catecumenato/ja-vem-o-meu-deus.json';
import pre_jerusalem_reconstruida from './pre-catecumenato/jerusalem-reconstruida.json';
import pre_leva_me_ao_ceu from './pre-catecumenato/leva-me-ao-ceu.json';
import pre_levanto_os_meus_olhos_para_os_montes from './pre-catecumenato/levanto-meus-olhos-para-os-montes.json';
import pre_louvai_o_senhor from './pre-catecumenato/louvai-o-senhor.json';
import pre_louvai_o_senhor_nos_ceus from './pre-catecumenato/louvai-o-senhor-nos-ceus.json';
import pre_magnificat from './pre-catecumenato/magnificat.json';
import pre_maria_casa_da_bencao from './pre-catecumenato/maria-casa-da-bencao.json';
import pre_maria_de_jasna_gora from './pre-catecumenato/maria-de-jasna-gora.json';
import pre_maria_mae_da_igreja from './pre-catecumenato/maria-mae-da-igreja.json';
import pre_maria_mae_do_caminho_ardente from './pre-catecumenato/maria-mae-do-caminho-ardente.json';
import pre_maria_pequena_maria from './pre-catecumenato/maria-pequena-maria.json';
import pre_maria_pomba_incorrupta from './pre-catecumenato/maria-pomba-incorrupta.json';
import pre_misericordia_minha_misericordia from './pre-catecumenato/misericordia-minha-misericordia.json';
import pre_mostrar_me_as_o_caminho_da_vida from './pre-catecumenato/mostrar-me-as-o-caminho-da-vida.json';
import pre_muito_me_perseguiram from './pre-catecumenato/muito-me-perseguiram.json';
import pre_nao_esta_aqui_ressuscitou from './pre-catecumenato/nao-esta-aqui-ressuscitou.json';
import pre_nao_ha_nele_aparencia from './pre-catecumenato/nao-ha-nele-aparencia.json';
import pre_o_ceus_chovei_do_alto from './pre-catecumenato/o-ceus-chovei-do-alto.json';
import pre_o_deus_pelo_teu_nome_salva_me from './pre-catecumenato/o-deus-pelo-teu-nome-salva-me.json';
import pre_o_deus_tu_es_meu_deus from './pre-catecumenato/o-deus-tu-es-meu-deus.json';
import pre_o_jesus_meu_amor from './pre-catecumenato/o-jesus-meu-amor.json';
import pre_o_morte_onde_esta_a_tua_vitoria from './pre-catecumenato/o-morte-onde-esta-tua-vitoria.json';
import pre_o_nescio_pensa_que_deus_nao_existe from './pre-catecumenato/o-nescio-pensa-que-deus-nao-existe.json';
import pre_o_povo_que_caminhava_nas_trevas from './pre-catecumenato/o-povo-que-caminhava-nas-trevas.json';
import pre_o_senhor_anuncia_uma_noticia from './pre-catecumenato/o-senhor-anuncia-uma-noticia.json';
import pre_o_senhor_e_meu_pastor from './pre-catecumenato/o-senhor-e-meu-pastor.json';
import pre_o_senhor_e_minha_luz_e_salvacao from './pre-catecumenato/o-senhor-e-minha-luz-e-salvacao.json';
import pre_o_senhor_nosso_deus from './pre-catecumenato/o-senhor-nosso-deus.json';
import pre_olhai_que_estupendo from './pre-catecumenato/olhai-que-estupendo.json';
import pre_os_meninos_de_belem from './pre-catecumenato/os-meninos-de-belem.json';
import pre_para_ti_morada_santa from './pre-catecumenato/para-ti-morada-santa.json';
import pre_pentecostes from './pre-catecumenato/pentecostes.json';
import pre_por_amor_de_meus_amigos from './pre-catecumenato/por-amor-de-meus-amigos.json';
import pre_por_que_confabulam_as_nacoes from './pre-catecumenato/por-que-confabulam-as-nacoes.json';
import pre_por_que_esta_noite_e_diferente from './pre-catecumenato/por-que-esta-noite-e-diferente.json';
import pre_porque_o_meu_jugo_e_suave from './pre-catecumenato/porque-o-meu-jugo-e-suave.json';
import pre_quando_israel_saiu_do_egito from './pre-catecumenato/quando-israel-saiu-do-egito.json';
import pre_quando_o_senhor from './pre-catecumenato/quando-o-senhor.json';
import pre_que_estupendo_que_alegria from './pre-catecumenato/que-estupendo-que-alegria.json';
import pre_quem_e_esta_que_sobe_do_deserto from './pre-catecumenato/quem-e-esta-que-sobe-do-deserto.json';
import pre_quem_nos_separara from './pre-catecumenato/quem-nos-separara.json';
import pre_quero_andar from './pre-catecumenato/quero-andar.json';
import pre_quero_cantar from './pre-catecumenato/quero-cantar.json';
import pre_ressuscitou from './pre-catecumenato/ressuscitou.json';
import pre_resurrexit from './pre-catecumenato/resurrexit.json';
import pre_salve_rainha from './pre-catecumenato/salve-rainha.json';
import pre_salve_rainha_dos_ceus from './pre-catecumenato/salve-rainha-dos-ceus.json';
import pre_se_hoje_escutardes_a_sua_voz from './pre-catecumenato/se-hoje-escutardes-a-sua-voz.json';
import pre_se_me_refugiei_no_senhor from './pre-catecumenato/se-me-refugiei-no-senhor.json';
import pre_se_o_senhor_nao_constroi_a_casa from './pre-catecumenato/se-o-senhor-nao-constroi-a-casa.json';
import pre_se_vos_ressuscitastes_com_cristo from './pre-catecumenato/se-vos-ressuscitastes-com-cristo.json';
import pre_seduziste_me_senhor from './pre-catecumenato/seduziste-me-senhor.json';
import pre_senhor_ajuda_me_a_nao_duvidar_de_ti from './pre-catecumenato/senhor-ajuda-me-a-nao-duvidar-de-ti.json';
import pre_senhor_nao_me_corrijas_na_tua_colera from './pre-catecumenato/senhor-nao-me-corrijas-na-sua-colera.json';
import pre_shlom_lej_mariam from './pre-catecumenato/shlom-lej-mariam.json';
import pre_siao_mae_de_todos_os_povos from './pre-catecumenato/siao-mae-de-todos-os-povos.json';
import pre_so_a_so from './pre-catecumenato/so-a-so.json';
import pre_sobe_deus_entre_aclamacoes from './pre-catecumenato/sobe-deus-entre-aclamacoes.json';
import pre_stabat_mater_dolorosa from './pre-catecumenato/stabat-mater-dolorosa.json';
import pre_tu_es_formoso from './pre-catecumenato/tu-es-formoso.json';
import pre_tu_que_es_fiel from './pre-catecumenato/tu-que-es-fiel.json';
import pre_um_grande_sinal from './pre-catecumenato/um-grande-sinal.json';
import pre_um_rebento_brota_do_tronco_de_jesse from './pre-catecumenato/um-rebento-brota-do-tronco-de-jesse.json';
import pre_uri_uri_uri_ura from './pre-catecumenato/uri-uri-uri-ura.json';
import pre_vamos_ja_pastores from './pre-catecumenato/vamos-ja-pastores.json';
import pre_vem_do_libano from './pre-catecumenato/vem-do-libano.json';
import pre_vem_espirito_santo from './pre-catecumenato/vem-espirito-santo.json';
import pre_vem_filho_do_homem from './pre-catecumenato/vem-filho-do-homem.json';
import pre_vem_o_senhor from './pre-catecumenato/vem-o-senhor.json';
import pre_veni_creator from './pre-catecumenato/veni-creator.json';
import pre_virgem_da_maravilha from './pre-catecumenato/virgem-da-maravilha.json';
import pre_vivei_alegres from './pre-catecumenato/vivei-alegres.json';
import pre_vos_sois_a_luz_do_mundo from './pre-catecumenato/vos-sois-a-luz-do-mundo.json';
import pre_vos_tomarei_dentre_as_nacoes from './pre-catecumenato/vos-tomarei-dentre-as-nacoes.json';
import pre_zaqueu from './pre-catecumenato/zaqueu.json';

const registry: Record<string, any> = {
  'catecumenato/as-armas-da-luz.json': cat_as_armas_da_luz,
  'catecumenato/assim-fala-o-amem.json': cat_assim_fala_o_amem,
  'catecumenato/bendito-seja-deus.json': cat_bendito_seja_deus,
  'catecumenato/como-o-impulso-que-sente-a-ira.json': cat_como_o_impulso_que_sente_a_ira,
  'catecumenato/como-ovelha-que-ve.json': cat_como_ovelha_que_ve,
  'catecumenato/consolai-o-meu-povo.json': cat_consolai_o_meu_povo,
  'catecumenato/debora.json': cat_debora,
  'catecumenato/eis-o-meu-servo.json': cat_eis_o_meu_servo,
  'catecumenato/eis-que-o-nosso-espelho-e-o-senhor.json': cat_eis_que_o_nosso_espelho_e_o_senhor,
  'catecumenato/escutai-ilhas-de-longe.json': cat_escutai_ilhas_de_longe,
  'catecumenato/hino-a-cruz-gloriosa.json': cat_hino_a_cruz_gloriosa,
  'catecumenato/jaco.json': cat_jaco,
  'catecumenato/nao-sofras-pelos-malvados.json': cat_nao_sofras_pelos_malvados,
  'catecumenato/ninguem-pode-servir-a-dois-senhores.json': cat_ninguem_pode_servir_a_dois_senhores,
  'catecumenato/o-combate-escatologico.json': cat_o_combate_escatologico,
  'catecumenato/o-lagareiro.json': cat_o_lagareiro,
  'catecumenato/o-mesmo-deus.json': cat_o_mesmo_deus,
  'catecumenato/o-semeador.json': cat_o_semeador,
  'catecumenato/o-senhor-me-deu.json': cat_o_senhor_me_deu,
  'catecumenato/o-senhor-meu-coracao-nao-e-pretensioso.json': cat_o_senhor_meu_coracao_nao_e_pretensioso,
  'catecumenato/quando-dormia.json': cat_quando_dormia,
  'catecumenato/senhor-tu-me-escrutas-e-conheces.json': cat_senhor_tu_me_escrutas_e_conheces,
  'catecumenato/senta-te-solitario-e-silencioso.json': cat_senta_te_solitario_e_silencioso,
  'catecumenato/shema-israel.json': cat_shema_israel,
  'catecumenato/tu-cobriste-de-vergonha-a-morte.json': cat_tu_cobriste_de_vergonha_a_morte,
  'catecumenato/tu-es-digno-de-receber-o-livro.json': cat_tu_es_digno_de_receber_o_livro,
  'eleicao/a-ceia-do-cordeiro.json': el_a_ceia_do_cordeiro,
  'eleicao/a-cordeira-de-deus.json': el_a_cordeira_de_deus,
  'eleicao/a-pomba-voou.json': el_a_pomba_voou,
  'eleicao/a-voz-do-meu-amado.json': el_a_voz_do_meu_amado,
  'eleicao/abba-pai.json': el_abba_pai,
  'eleicao/como-condenados-a-morte.json': el_como_condenados_a_morte,
  'eleicao/como-escorre-o-mel.json': el_como_escorre_o_mel,
  'eleicao/como-lirio-entre-espinhos.json': el_como_lirio_entre_espinhos,
  'eleicao/estendo-minhas-maos.json': el_estendo_minhas_maos,
  'eleicao/formosa-es-amiga-minha.json': el_formosa_es_amiga_minha,
  'eleicao/hino-a-caridade.json': el_hino_a_caridade,
  'eleicao/jesus-percorria-todas-as-cidades.json': el_jesus_percorria_todas_as_cidades,
  'eleicao/nao-resistais-ao-mal.json': el_nao_resistais_ao_mal,
  'eleicao/noli-me-tangere.json': el_noli_me_tangere,
  'eleicao/o-espirito-do-senhor-esta-sobre-mim.json': el_o_espirito_do_senhor_esta_sobre_mim,
  'eleicao/o-messias-leao-para-vencer.json': el_o_messias_leao_para_vencer,
  'eleicao/roubaste-meu-coracao.json': el_roubaste_o_meu_coracao,
  'eleicao/sermao-da-montanha.json': el_sermao_da_montanha,
  'eleicao/tu-es-a-minha-esperanca-senhor.json': el_tu_es_a_minha_esperanca_senhor,
  'liturgia/aleluia-interleccional.json': li_aleluia_interlecional,
  'liturgia/aleluia-pascal.json': li_aleluia_pascal,
  'liturgia/aleluia-pascal-ii.json': li_aleluia_pascal_ii,
  'liturgia/anafora-do-sal.json': li_anafora_do_sal,
  'liturgia/antifona-versiculo-antes-do-evangelho.json': li_antifona_versiculo_antes_do_evangelho,
  'liturgia/bencao-da-agua.json': li_bencao_da_agua,
  'liturgia/bencao-penitencial.json': li_bencao_penitencial,
  'liturgia/cordeiro-de-deus.json': li_cordeiro_de_deus,
  'liturgia/credo.json': li_credo,
  'liturgia/gloria-a-deus-no-alto-do-ceu.json': li_gloria_a_deus_no_alto_do_ceu,
  'liturgia/hino-das-laudes-de-pentecostes.json': li_hino_das_laudes_de_pentecostes,
  'liturgia/ladainha-de-todos-os-santos.json': li_ladainha_de_todos_os_santos,
  'liturgia/ladainha-penitencial-i.json': li_ladainha_penitencial_i,
  'liturgia/ladainha-penitencial-ii.json': li_ladainha_penitencial_ii,
  'liturgia/oracao-eucaristica-ii.json': li_oracao_eucaristica_ii,
  'liturgia/oracao-eucaristica-iv.json': li_oracao_eucaristica_iv,
  'liturgia/pai-nosso.json': li_pai_nosso,
  'liturgia/preconio-pascal.json': li_preconio_pascal,
  'liturgia/prefacio-da-pascoa-i.json': li_prefacio_da_pascoa_i,
  'liturgia/prefacio-do-advento-i.json': li_prefacio_do_advento_i,
  'liturgia/prefacio-do-advento-ii.json': li_prefacio_do_advento_ii,
  'liturgia/prefacio-do-natal-do-senhor-i.json': li_prefacio_do_natal_do_senhor_i,
  'liturgia/salmodia-para-as-oracoes-universais.json': li_salmodia_para_as_oracoes_universais,
  'liturgia/salmodia-para-o-salmo-responsorial.json': li_salmodia_para_o_salmo_responsorial,
  'liturgia/santo-1982.json': li_santo_1982,
  'liturgia/santo-1988.json': li_santo_1988,
  'liturgia/santo-hebraico.json': li_santo_hebraico,
  'liturgia/santo-palestina-74.json': li_santo_palestina_74,
  'liturgia/santo-palomeras-65.json': li_santo_palomeras_65,
  'liturgia/santo-roma-77.json': li_santo_roma_77,
  'liturgia/te-deum.json': li_te_deum,
  'pre-catecumenato/a-cabana-dos-pastores.json': pre_a_cabana_dos_pastores,
  'pre-catecumenato/a-ceifa-das-nacoes.json': pre_a_ceifa_das_nacoes,
  'pre-catecumenato/a-espada.json': pre_a_espada,
  'pre-catecumenato/a-marcha-e-dura.json': pre_a_marcha_e_dura,
  'pre-catecumenato/a-ninguem-demos-ocasiao-de-tropeco.json': pre_a_ninguem_demos_ocasiao_de_tropeco,
  'pre-catecumenato/a-ti-levanto-meus-olhos.json': pre_a_ti_levanto_meus_olhos,
  'pre-catecumenato/a-ti-senhor-com-minha-voz-gritando-imploro.json': pre_a_ti_senhor_com_minha_voz_gritando_imploro,
  'pre-catecumenato/a-ti-senhor-levanto-minha-alma.json': pre_a_ti_senhor_levanto_minha_alma,
  'pre-catecumenato/a-ti-senhor-se-deve-o-louvor-em-siao.json': pre_a_ti_senhor_se_deve_o_louvor_em_siao,
  'pre-catecumenato/a-vitima-pascal.json': pre_a_vitima_pascal,
  'pre-catecumenato/abraao.json': pre_abraao,
  'pre-catecumenato/aclamai-o-senhor.json': pre_aclamai_o_senhor,
  'pre-catecumenato/akeda.json': pre_akeda,
  'pre-catecumenato/alcai-o-portas.json': pre_alcai_o_portas,
  'pre-catecumenato/aleluia-bendizei-o-senhor.json': pre_aleluia_bendizei_o_senhor,
  'pre-catecumenato/aleluia-ja-chegou-o-reino.json': pre_aleluia_ja_chegou_o_reino,
  'pre-catecumenato/aleluia-louvai-o-senhor.json': pre_aleluia_louvai_o_senhor,
  'pre-catecumenato/amem-amem-amem.json': pre_amem_amem_amem,
  'pre-catecumenato/amo-o-senhor.json': pre_amo_o_senhor,
  'pre-catecumenato/ao-despertar.json': pre_ao_despertar,
  'pre-catecumenato/ate-quando.json': pre_ate_quando,
  'pre-catecumenato/ave-maria-i.json': pre_ave_maria_i,
  'pre-catecumenato/ave-maria-ii-1984.json': pre_ave_maria_ii_1984,
  'pre-catecumenato/babilonia-criminal.json': pre_babilonia_criminal,
  'pre-catecumenato/balaao.json': pre_balaao,
  'pre-catecumenato/bendirei-o-senhor-em-todo-tempo.json': pre_bendirei_o_senhor_em_todo_tempo,
  'pre-catecumenato/bendita-es-tu-maria.json': pre_bendita_es_tu_maria,
  'pre-catecumenato/bendito-sejas-senhor.json': pre_bendito_sejas_senhor,
  'pre-catecumenato/bendize-minha-alma-a-iahweh.json': pre_bendize_minha_alma_a_iahweh,
  'pre-catecumenato/benedictus.json': pre_benedictus,
  'pre-catecumenato/canta-a-iahweh-jerusalem.json': pre_canta_a_iahweh_jerusalem,
  'pre-catecumenato/cantico-de-ana.json': pre_cantico_de_ana,
  'pre-catecumenato/cantico-dos-tres-jovens.json': pre_cantico_dos_tres_jovens,
  'pre-catecumenato/canto-de-moises.json': pre_canto_de_moises,
  'pre-catecumenato/caritas-christi-urget-nos.json': pre_caritas_christi_urget_nos,
  'pre-catecumenato/chegue-a-tua-presenca-o-meu-clamor.json': pre_chegue_a_tua_presenca_meu_clamor,
  'pre-catecumenato/como-a-corca.json': pre_como_a_corca,
  'pre-catecumenato/como-e-maravilhoso.json': pre_como_e_maravilhoso,
  'pre-catecumenato/como-sao-amaveis-tuas-moradas.json': pre_como_sao_amaveis_tuas_moradas,
  'pre-catecumenato/confessei-a-ti-o-meu-pecado.json': pre_confessei_a_ti_o_meu_pecado,
  'pre-catecumenato/dayenu.json': pre_dayenu,
  'pre-catecumenato/de-profundis.json': pre_de_profundis,
  'pre-catecumenato/dia-de-repouso.json': pre_dia_de_repouso,
  'pre-catecumenato/diante-dos-anjos.json': pre_diante_dos_anjos,
  'pre-catecumenato/diz-o-senhor-ao-meu-senhor.json': pre_diz_o_senhor_ao_meu_senhor,
  'pre-catecumenato/dizei-aos-de-coracao-cansado.json': pre_dizei_aos_de_coracao_cansado,
  'pre-catecumenato/e-paciente.json': pre_e_paciente,
  'pre-catecumenato/eis-me-aqui-que-venho-em-breve.json': pre_eis_me_aqui_que_venho_em_breve,
  'pre-catecumenato/eli-eli-lama-sabatani.json': pre_eli_eli_lama_sabactani,
  'pre-catecumenato/em-meio-a-multidao.json': pre_em_meio_a_multidao,
  'pre-catecumenato/em-tua-luz-senhor-vemos-a-luz.json': pre_em_tua_luz_senhor_vemos_a_luz,
  'pre-catecumenato/em-uma-noite-escura.json': pre_em_uma_noite_escura,
  'pre-catecumenato/encontraram-se-dois-anjos.json': pre_encontraram_se_dois_anjos,
  'pre-catecumenato/esconde-me-no-oculto-de-tua-tenda.json': pre_esconde_me_no_oculto_de_tua_tenda,
  'pre-catecumenato/esperei-esperei-no-senhor.json': pre_esperei_esperei_no_senhor,
  'pre-catecumenato/estao-rotas-minhas-ataduras.json': pre_estao_rotas_minhas_ataduras,
  'pre-catecumenato/este-e-o-dia-que-fez-o-senhor.json': pre_este_e_o_dia_que_fez_o_senhor,
  'pre-catecumenato/este-e-o-meu-mandamento.json': pre_este_e_o_meu_mandamento,
  'pre-catecumenato/estou-chamando-te.json': pre_estou_chamando_te,
  'pre-catecumenato/eu-te-amo-senhor.json': pre_eu_te_amo_senhor,
  'pre-catecumenato/eu-venho-reunir.json': pre_eu_venho_reunir,
  'pre-catecumenato/evenu-shalom-alehem.json': pre_evenu_shalom_alehem,
  'pre-catecumenato/exultai-justos-no-senhor.json': pre_exultai_justos_no_senhor,
  'pre-catecumenato/felicidade-para-o-homem.json': pre_felicidade_para_o_homem,
  'pre-catecumenato/feliz-o-homem.json': pre_feliz_o_homem,
  'pre-catecumenato/filhas-de-jerusalem.json': pre_filhas_de_jerusalem,
  'pre-catecumenato/foge-o-meu-amado.json': pre_foge_o_meu_amado,
  'pre-catecumenato/gracas-a-iahweh.json': pre_gracas_a_iahweh,
  'pre-catecumenato/gritai-jubilosos.json': pre_gritai_jubilosos,
  'pre-catecumenato/hino-a-cristo-luz.json': pre_hino_a_cristo_luz,
  'pre-catecumenato/hino-a-kenosis.json': pre_hino_a_kenosis,
  'pre-catecumenato/hino-da-ascensao.json': pre_hino_da_ascensao,
  'pre-catecumenato/hino-da-pascoa.json': pre_hino_da_pascoa,
  'pre-catecumenato/hino-do-advento.json': pre_hino_do_advento,
  'pre-catecumenato/iahweh-tu-es-meu-deus.json': pre_iahweh_tu_es_meu_deus,
  'pre-catecumenato/ide-e-anunciai-a-meus-irmaos.json': pre_ide_e_anunciai_a_meus_irmaos,
  'pre-catecumenato/improperios.json': pre_improperios,
  'pre-catecumenato/ja-vem-o-meu-deus.json': pre_ja_vem_o_meu_deus,
  'pre-catecumenato/jerusalem-reconstruida.json': pre_jerusalem_reconstruida,
  'pre-catecumenato/leva-me-ao-ceu.json': pre_leva_me_ao_ceu,
  'pre-catecumenato/levanto-meus-olhos-para-os-montes.json': pre_levanto_os_meus_olhos_para_os_montes,
  'pre-catecumenato/louvai-o-senhor.json': pre_louvai_o_senhor,
  'pre-catecumenato/louvai-o-senhor-nos-ceus.json': pre_louvai_o_senhor_nos_ceus,
  'pre-catecumenato/magnificat.json': pre_magnificat,
  'pre-catecumenato/maria-casa-da-bencao.json': pre_maria_casa_da_bencao,
  'pre-catecumenato/maria-de-jasna-gora.json': pre_maria_de_jasna_gora,
  'pre-catecumenato/maria-mae-da-igreja.json': pre_maria_mae_da_igreja,
  'pre-catecumenato/maria-mae-do-caminho-ardente.json': pre_maria_mae_do_caminho_ardente,
  'pre-catecumenato/maria-pequena-maria.json': pre_maria_pequena_maria,
  'pre-catecumenato/maria-pomba-incorrupta.json': pre_maria_pomba_incorrupta,
  'pre-catecumenato/misericordia-minha-misericordia.json': pre_misericordia_minha_misericordia,
  'pre-catecumenato/mostrar-me-as-o-caminho-da-vida.json': pre_mostrar_me_as_o_caminho_da_vida,
  'pre-catecumenato/muito-me-perseguiram.json': pre_muito_me_perseguiram,
  'pre-catecumenato/nao-esta-aqui-ressuscitou.json': pre_nao_esta_aqui_ressuscitou,
  'pre-catecumenato/nao-ha-nele-aparencia.json': pre_nao_ha_nele_aparencia,
  'pre-catecumenato/o-ceus-chovei-do-alto.json': pre_o_ceus_chovei_do_alto,
  'pre-catecumenato/o-deus-pelo-teu-nome-salva-me.json': pre_o_deus_pelo_teu_nome_salva_me,
  'pre-catecumenato/o-deus-tu-es-meu-deus.json': pre_o_deus_tu_es_meu_deus,
  'pre-catecumenato/o-jesus-meu-amor.json': pre_o_jesus_meu_amor,
  'pre-catecumenato/o-morte-onde-esta-tua-vitoria.json': pre_o_morte_onde_esta_a_tua_vitoria,
  'pre-catecumenato/o-nescio-pensa-que-deus-nao-existe.json': pre_o_nescio_pensa_que_deus_nao_existe,
  'pre-catecumenato/o-povo-que-caminhava-nas-trevas.json': pre_o_povo_que_caminhava_nas_trevas,
  'pre-catecumenato/o-senhor-anuncia-uma-noticia.json': pre_o_senhor_anuncia_uma_noticia,
  'pre-catecumenato/o-senhor-e-meu-pastor.json': pre_o_senhor_e_meu_pastor,
  'pre-catecumenato/o-senhor-e-minha-luz-e-salvacao.json': pre_o_senhor_e_minha_luz_e_salvacao,
  'pre-catecumenato/o-senhor-nosso-deus.json': pre_o_senhor_nosso_deus,
  'pre-catecumenato/olhai-que-estupendo.json': pre_olhai_que_estupendo,
  'pre-catecumenato/os-meninos-de-belem.json': pre_os_meninos_de_belem,
  'pre-catecumenato/para-ti-morada-santa.json': pre_para_ti_morada_santa,
  'pre-catecumenato/pentecostes.json': pre_pentecostes,
  'pre-catecumenato/por-amor-de-meus-amigos.json': pre_por_amor_de_meus_amigos,
  'pre-catecumenato/por-que-confabulam-as-nacoes.json': pre_por_que_confabulam_as_nacoes,
  'pre-catecumenato/por-que-esta-noite-e-diferente.json': pre_por_que_esta_noite_e_diferente,
  'pre-catecumenato/porque-o-meu-jugo-e-suave.json': pre_porque_o_meu_jugo_e_suave,
  'pre-catecumenato/quando-israel-saiu-do-egito.json': pre_quando_israel_saiu_do_egito,
  'pre-catecumenato/quando-o-senhor.json': pre_quando_o_senhor,
  'pre-catecumenato/que-estupendo-que-alegria.json': pre_que_estupendo_que_alegria,
  'pre-catecumenato/quem-e-esta-que-sobe-do-deserto.json': pre_quem_e_esta_que_sobe_do_deserto,
  'pre-catecumenato/quem-nos-separara.json': pre_quem_nos_separara,
  'pre-catecumenato/quero-andar.json': pre_quero_andar,
  'pre-catecumenato/quero-cantar.json': pre_quero_cantar,
  'pre-catecumenato/ressuscitou.json': pre_ressuscitou,
  'pre-catecumenato/resurrexit.json': pre_resurrexit,
  'pre-catecumenato/salve-rainha.json': pre_salve_rainha,
  'pre-catecumenato/salve-rainha-dos-ceus.json': pre_salve_rainha_dos_ceus,
  'pre-catecumenato/se-hoje-escutardes-a-sua-voz.json': pre_se_hoje_escutardes_a_sua_voz,
  'pre-catecumenato/se-me-refugiei-no-senhor.json': pre_se_me_refugiei_no_senhor,
  'pre-catecumenato/se-o-senhor-nao-constroi-a-casa.json': pre_se_o_senhor_nao_constroi_a_casa,
  'pre-catecumenato/se-vos-ressuscitastes-com-cristo.json': pre_se_vos_ressuscitastes_com_cristo,
  'pre-catecumenato/seduziste-me-senhor.json': pre_seduziste_me_senhor,
  'pre-catecumenato/senhor-ajuda-me-a-nao-duvidar-de-ti.json': pre_senhor_ajuda_me_a_nao_duvidar_de_ti,
  'pre-catecumenato/senhor-nao-me-corrijas-na-sua-colera.json': pre_senhor_nao_me_corrijas_na_tua_colera,
  'pre-catecumenato/shlom-lej-mariam.json': pre_shlom_lej_mariam,
  'pre-catecumenato/siao-mae-de-todos-os-povos.json': pre_siao_mae_de_todos_os_povos,
  'pre-catecumenato/so-a-so.json': pre_so_a_so,
  'pre-catecumenato/sobe-deus-entre-aclamacoes.json': pre_sobe_deus_entre_aclamacoes,
  'pre-catecumenato/stabat-mater-dolorosa.json': pre_stabat_mater_dolorosa,
  'pre-catecumenato/tu-es-formoso.json': pre_tu_es_formoso,
  'pre-catecumenato/tu-que-es-fiel.json': pre_tu_que_es_fiel,
  'pre-catecumenato/um-grande-sinal.json': pre_um_grande_sinal,
  'pre-catecumenato/um-rebento-brota-do-tronco-de-jesse.json': pre_um_rebento_brota_do_tronco_de_jesse,
  'pre-catecumenato/uri-uri-uri-ura.json': pre_uri_uri_uri_ura,
  'pre-catecumenato/vamos-ja-pastores.json': pre_vamos_ja_pastores,
  'pre-catecumenato/vem-do-libano.json': pre_vem_do_libano,
  'pre-catecumenato/vem-espirito-santo.json': pre_vem_espirito_santo,
  'pre-catecumenato/vem-filho-do-homem.json': pre_vem_filho_do_homem,
  'pre-catecumenato/vem-o-senhor.json': pre_vem_o_senhor,
  'pre-catecumenato/veni-creator.json': pre_veni_creator,
  'pre-catecumenato/virgem-da-maravilha.json': pre_virgem_da_maravilha,
  'pre-catecumenato/vivei-alegres.json': pre_vivei_alegres,
  'pre-catecumenato/vos-sois-a-luz-do-mundo.json': pre_vos_sois_a_luz_do_mundo,
  'pre-catecumenato/vos-tomarei-dentre-as-nacoes.json': pre_vos_tomarei_dentre_as_nacoes,
  'pre-catecumenato/zaqueu.json': pre_zaqueu,
};

export function getSongByFile(file: string): any | undefined {
  return registry[file];
}
